### ISSUE TITLE
Custom delimiter option

### ISSUE THREAD

**Issue by andreystepanov** [ChrisPenner/lens-csv#10]
Hi, Chris

First, thanks for the package.
Second thanks goes for the book `Optics By Example`, which i purchased recently and currently working through.

Is there's a way to pass custom delimiter as an option to underlying `cassava` package using `lens-csv`?

**Comment by ChrisPenner** [comment]
Hello! Glad you're enjoying it!

Yes, you can use a decoder of your choice from Cassava itself, e.g. https://hackage.haskell.org/package/cassava-0.5.1.0/docs/Data-Csv.html#v:decodeByNameWith , takes a `DecodeOptions`, then use the corresponding converter in `lens-csv`; see the example here: https://hackage.haskell.org/package/lens-csv-0.1.1.0/docs/Data-Csv-Lens.html#v:cassavaNamed

**Comment by andreystepanov** [comment]
I should've looked at Hackage docs closely, before asking my silly question :)
Thanks anyway!
